<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CurrencySeeder extends Seeder
{
    public function run(): void
    {
        $currencies = [
            // Top 6 fiat
            [
                'currency_code' => 'CAD',
                'numeric_code' => '124',
                'name' => 'Canadian Dollar',
                'symbol' => 'C$',
                'type' => 'fiat',
                'scale' => 6,
                'display_scale' => 2,
            ],
            [
                'currency_code' => 'USD',
                'numeric_code' => '840',
                'name' => 'US Dollar',
                'symbol' => '$',
                'type' => 'fiat',
                'scale' => 6,
                'display_scale' => 2,
            ],
            [
                'currency_code' => 'EUR',
                'numeric_code' => '978',
                'name' => 'Euro',
                'symbol' => '€',
                'type' => 'fiat',
                'scale' => 6,
                'display_scale' => 2,
            ],
            [
                'currency_code' => 'JPY',
                'numeric_code' => '392',
                'name' => 'Japanese Yen',
                'symbol' => '¥',
                'type' => 'fiat',
                'scale' => 6,
                'display_scale' => 0,
            ],
            [
                'currency_code' => 'GBP',
                'numeric_code' => '826',
                'name' => 'British Pound',
                'symbol' => '£',
                'type' => 'fiat',
                'scale' => 6,
                'display_scale' => 2,
            ],
            [
                'currency_code' => 'AUD',
                'numeric_code' => '036',
                'name' => 'Australian Dollar',
                'symbol' => 'A$',
                'type' => 'fiat',
                'scale' => 6,
                'display_scale' => 2,
            ],

            // Top 10 crypto
            [
                'currency_code' => 'BTC',
                'numeric_code' => null,
                'name' => 'Bitcoin',
                'symbol' => '₿',
                'type' => 'crypto',
                'scale' => 18,
                'display_scale' => 8,
            ],
            [
                'currency_code' => 'ETH',
                'numeric_code' => null,
                'name' => 'Ethereum',
                'symbol' => 'Ξ',
                'type' => 'crypto',
                'scale' => 18,
                'display_scale' => 8,
            ],
            [
                'currency_code' => 'USDT',
                'numeric_code' => null,
                'name' => 'Tether',
                'symbol' => '₮',
                'type' => 'crypto',
                'scale' => 18,
                'display_scale' => 6,
            ],
            [
                'currency_code' => 'BNB',
                'numeric_code' => null,
                'name' => 'BNB',
                'symbol' => 'BNB',
                'type' => 'crypto',
                'scale' => 18,
                'display_scale' => 8,
            ],
            [
                'currency_code' => 'XRP',
                'numeric_code' => null,
                'name' => 'XRP',
                'symbol' => 'XRP',
                'type' => 'crypto',
                'scale' => 18,
                'display_scale' => 6,
            ],
            [
                'currency_code' => 'USDC',
                'numeric_code' => null,
                'name' => 'USD Coin',
                'symbol' => '$',
                'type' => 'crypto',
                'scale' => 18,
                'display_scale' => 6,
            ],
            [
                'currency_code' => 'SOL',
                'numeric_code' => null,
                'name' => 'Solana',
                'symbol' => '◎',
                'type' => 'crypto',
                'scale' => 18,
                'display_scale' => 8,
            ],
            [
                'currency_code' => 'DOGE',
                'numeric_code' => null,
                'name' => 'Dogecoin',
                'symbol' => 'Ð',
                'type' => 'crypto',
                'scale' => 18,
                'display_scale' => 8,
            ],
            [
                'currency_code' => 'TRX',
                'numeric_code' => null,
                'name' => 'TRON',
                'symbol' => 'TRX',
                'type' => 'crypto',
                'scale' => 18,
                'display_scale' => 6,
            ],
            [
                'currency_code' => 'ADA',
                'numeric_code' => null,
                'name' => 'Cardano',
                'symbol' => '₳',
                'type' => 'crypto',
                'scale' => 18,
                'display_scale' => 6,
            ],
            [
                'currency_code' => 'XMR',
                'numeric_code' => null,
                'name' => 'Monero',
                'symbol' => 'XMR',
                'type' => 'crypto',
                'scale' => 18,
                'display_scale' => 8,
            ],
            [
                'currency_code' => 'ARRR',
                'numeric_code' => null,
                'name' => 'Pirate Chain',
                'symbol' => 'ARRR',
                'type' => 'crypto',
                'scale' => 18,
                'display_scale' => 8,
            ],
            [
                'currency_code' => 'DERO',
                'numeric_code' => null,
                'name' => 'Dero',
                'symbol' => 'DERO',
                'type' => 'crypto',
                'scale' => 18,
                'display_scale' => 8,
            ],
            [
                'currency_code' => 'XEQ',
                'numeric_code' => null,
                'name' => 'Equilibria',
                'symbol' => 'XEQ',
                'type' => 'crypto',
                'scale' => 18,
                'display_scale' => 8,
            ],
            [
                'currency_code' => 'XNO',
                'numeric_code' => null,
                'name' => 'Nano',
                'symbol' => 'XNO',
                'type' => 'crypto',
                'scale' => 18,
                'display_scale' => 30,
            ],
            [
                'currency_code' => 'VRSC',
                'numeric_code' => null,
                'name' => 'Verus Coin',
                'symbol' => 'VRSC',
                'type' => 'crypto',
                'scale' => 18,
                'display_scale' => 8,
            ],
            [
                'currency_code' => 'RYO',
                'numeric_code' => null,
                'name' => 'Ryo',
                'symbol' => 'RYO',
                'type' => 'crypto',
                'scale' => 18,
                'display_scale' => 18,
            ],
            [
                'currency_code' => 'LTC',
                'numeric_code' => null,
                'name' => 'Litecoin',
                'symbol' => 'LTC',
                'type' => 'crypto',
                'scale' => 18,
                'display_scale' => 8,
            ],
            [
                'currency_code' => 'AVN',
                'numeric_code' => null,
                'name' => 'Avian',
                'symbol' => 'AVN',
                'type' => 'crypto',
                'scale' => 18,
                'display_scale' => 8,
            ],
            [
                'currency_code' => 'RXD',
                'numeric_code' => null,
                'name' => 'Radiant',
                'symbol' => 'RXD',
                'type' => 'crypto',
                'scale' => 18,
                'display_scale' => 8,
            ],
            [
                'currency_code' => 'RTM',
                'numeric_code' => null,
                'name' => 'Raptoreum',
                'symbol' => 'RTM',
                'type' => 'crypto',
                'scale' => 18,
                'display_scale' => 8,
            ],
            [
                'currency_code' => 'BUSD',
                'numeric_code' => null,
                'name' => 'Binance USD',
                'symbol' => 'BUSD',
                'type' => 'crypto',
                'scale' => 18,
                'display_scale' => 8,
            ],
        ];

        DB::table('currencies')->insert($currencies);
    }
}
