<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UploadedFilesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $files = [
            [
                'filename' => 'monero-txs.csv',
                'directory' => 'exports/monero',
                'mapper' => 'Monero',
                'platform' => 'Monero',
                'wallet' => 'XMR',
                'wallet_prefix' => null,
                'status' => 'pending',
            ],
            [
                'filename' => 'BitcoinCore TradeOgre.csv',
                'directory' => 'exports/bitcoin',
                'mapper' => 'BitcoinCore',
                'platform' => 'Bitcoin Core',
                'wallet' => 'TradeOgre',
                'wallet_prefix' => null,
                'status' => 'pending',
            ],
            [
                'filename' => 'BitcoinCore Hodlings.csv',
                'directory' => 'exports/bitcoin',
                'mapper' => 'BitcoinCore',
                'platform' => 'Bitcoin Core',
                'wallet' => 'Hodlings',
                'wallet_prefix' => null,
                'status' => 'pending',
            ],
            [
                'filename' => 'exodus-bitcoin-final.csv',
                'directory' => 'exports/exodus',
                'mapper' => 'Exodus',
                'platform' => 'Exodus',
                'wallet' => 'BTC',
                'wallet_prefix' => null,
                'status' => 'pending',
            ],
            [
                'filename' => 'exodus-ethereum-final.csv',
                'directory' => 'exports/exodus',
                'mapper' => 'Exodus',
                'platform' => 'Exodus',
                'wallet' => 'ETH',
                'wallet_prefix' => null,
                'status' => 'pending',
            ],
            [
                'filename' => 'exodus_0-cardano-txs-2022-05-15_19-56-08.csv',
                'directory' => 'exports/exodus',
                'mapper' => 'Exodus',
                'platform' => 'Exodus',
                'wallet' => 'ADA',
                'wallet_prefix' => null,
                'status' => 'pending',
            ],
            [
                'filename' => 'exodus_bnb.csv',
                'directory' => 'exports/exodus',
                'mapper' => 'Exodus',
                'platform' => 'Exodus',
                'wallet' => 'BNB',
                'wallet_prefix' => null,
                'status' => 'pending',
            ],
            [
                'filename' => 'bitcoin-atomicwallet-final.csv',
                'directory' => 'exports/atomic',
                'mapper' => 'Atomic',
                'platform' => 'Atomic Wallet',
                'wallet' => 'BTC',
                'wallet_prefix' => null,
                'status' => 'pending',
            ],
            [
                'filename' => 'binance_usd-atomicwallet-12.03.2022.csv',
                'directory' => 'exports/atomic',
                'mapper' => 'Atomic',
                'platform' => 'Atomic Wallet',
                'wallet' => 'BUSD',
                'wallet_prefix' => null,
                'status' => 'pending',
            ],
            [
                'filename' => 'ripple-atomicwallet-12.03.2022.csv',
                'directory' => 'exports/atomic',
                'mapper' => 'Atomic',
                'platform' => 'Atomic Wallet',
                'wallet' => 'XRP',
                'wallet_prefix' => null,
                'status' => 'pending',
            ],
            [
                'filename' => 'cardano-atomicwallet-12.03.2022.csv',
                'directory' => 'exports/atomic',
                'mapper' => 'Atomic',
                'platform' => 'Atomic Wallet',
                'wallet' => 'ADA',
                'wallet_prefix' => null,
                'status' => 'pending',
            ],
            [
                'filename' => 'ethereum-atomicwallet-final.csv',
                'directory' => 'exports/atomic',
                'mapper' => 'Atomic',
                'platform' => 'Atomic Wallet',
                'wallet' => 'ETH',
                'wallet_prefix' => null,
                'status' => 'pending',
            ],
            [
                'filename' => 'crypto_transactions_summary.csv',
                'directory' => 'exports/shakepay',
                'mapper' => 'ShakepayCrypto',
                'platform' => 'Shakepay',
                'wallet' => null,
                'wallet_prefix' => null,
                'status' => 'pending',
            ],
            [
                'filename' => 'cash_transactions_summary.csv',
                'directory' => 'exports/shakepay',
                'mapper' => 'ShakepayCash',
                'platform' => 'Shakepay',
                'wallet' => 'CAD',
                'wallet_prefix' => null,
                'status' => 'pending',
            ],
            [
                'filename' => 'export_withdrawals.csv',
                'directory' => 'exports/tradeogre',
                'mapper' => 'TradeOgreWithdrawal',
                'platform' => 'TradeOgre',
                'wallet' => null,
                'wallet_prefix' => null,
                'status' => 'pending',
            ],
            [
                'filename' => 'export_deposits.csv',
                'directory' => 'exports/tradeogre',
                'mapper' => 'TradeOgreDeposit',
                'platform' => 'TradeOgre',
                'wallet' => null,
                'wallet_prefix' => null,
                'status' => 'pending',
            ],
            [
                'filename' => 'export_trades.csv',
                'directory' => 'exports/tradeogre',
                'mapper' => 'TradeOgreTrade',
                'platform' => 'TradeOgre',
                'wallet' => null,
                'wallet_prefix' => null,
                'status' => 'pending',
            ],
            [
                'filename' => 'treasure_chest_2022-03-05.csv',
                'directory' => 'exports/treasure-chest',
                'mapper' => 'TreasureChest',
                'platform' => 'Treasure Chest',
                'wallet' => 'ARRR',
                'wallet_prefix' => null,
                'status' => 'pending',
            ],
            [
                'filename' => 'Avian.csv',
                'directory' => 'exports/avian',
                'mapper' => 'Avian',
                'platform' => 'Avian',
                'wallet' => 'AVN',
                'wallet_prefix' => null,
                'status' => 'pending',
            ],
            [
                'filename' => 'exodus-xmr.csv',
                'directory' => 'exports/exodus',
                'mapper' => 'Exodus',
                'platform' => 'Exodus',
                'wallet' => 'XMR',
                'wallet_prefix' => null,
                'status' => 'pending',
            ],
            [
                'filename' => 'Raptoreum.csv',
                'directory' => 'exports/raptoreum',
                'mapper' => 'Raptoreum',
                'platform' => 'Raptoreum',
                'wallet' => 'RTM',
                'wallet_prefix' => null,
                'status' => 'pending',
            ],
            [
                'filename' => 'Changelly-io.csv',
                'directory' => 'exports/generic',
                'mapper' => 'GenericIO',
                'platform' => 'Changelly',
                'wallet' => null,
                'wallet_prefix' => null,
                'status' => 'pending',
            ],
            [
                'filename' => 'Changelly-trades.csv',
                'directory' => 'exports/generic',
                'mapper' => 'GenericTrade',
                'platform' => 'Changelly',
                'wallet' => null,
                'wallet_prefix' => null,
                'status' => 'pending',
            ],
            [
                'filename' => 'Account History_Funding Account.csv',
                'directory' => 'exports/kucoin',
                'mapper' => 'KuCoin',
                'platform' => 'KuCoin',
                'wallet' => null,
                'wallet_prefix' => 'Funding',
                'status' => 'pending',
            ],
            [
                'filename' => 'Account History_Trading Account.csv',
                'directory' => 'exports/kucoin',
                'mapper' => 'KuCoin',
                'platform' => 'KuCoin',
                'wallet' => null,
                'wallet_prefix' => 'Trading',
                'status' => 'pending',
            ],
            [
                'filename' => 'Account History_Cross Margin Account.csv',
                'directory' => 'exports/kucoin',
                'mapper' => 'KuCoin',
                'platform' => 'KuCoin',
                'wallet' => null,
                'wallet_prefix' => 'Margin',
                'status' => 'pending',
            ],
            [
                'filename' => 'kraken_transfers.csv',
                'directory' => 'exports/kraken',
                'mapper' => 'PlatformTransfer',
                'platform' => 'Kraken',
                'wallet' => null,
                'wallet_prefix' => null,
                'status' => 'pending',
            ],
            [
                'filename' => 'kraken_trades.csv',
                'directory' => 'exports/kraken',
                'mapper' => 'PlatformTrade',
                'platform' => 'Kraken',
                'wallet' => null,
                'wallet_prefix' => null,
                'status' => 'pending',
            ],
        ];
        DB::table('uploaded_files')->insert($files);
    }
}
