#!/bin/bash

hostname=`hostname`

#if [ "$hostname" == "ds-mint" ]; then
    php artisan view:clear
    php artisan cache:clear
    php artisan clear-compiled
#else
#    php artisan view:clear
#    php artisan cache:clear
#    php artisan clear-compiled
#    php artisan optimize
#fi

